### ISSUE TITLE
Add depsy as a submodule

### ISSUE THREAD

**Issue by craigmaclachlan** [lbillingham/commit_opener#10]
I think it would be useful to add the depsy project as a submodule. This would make it easy to use their existing code and edit it if necessary.

[Instructions](https://gist.github.com/gitaarik/8735255)

**Comment by craigmaclachlan** [comment]
Hi Laurence, Could you do this?

**Comment by lbillingham** [comment]
Sure

**Comment by craigmaclachlan** [comment]
Done.
