### ISSUE TITLE
scrape meta data from repo

### ISSUE THREAD

**Issue by lbillingham** [lbillingham/commit_opener#2]
probably want (Git Python)[https://pypi.python.org/pypi/GitPython/]

want to populate`usernames`, `earliest commit`, `latest commit`, `commits_per_day`

and expose as `json`

**Comment by craigmaclachlan** [comment]
OK, I think the data scraping that depsy does, is done by the scripts in the "scripts" directory:
https://github.com/Impactstory/depsy/tree/master/scripts

**Comment by ghost** [comment]
Other options are ...

**How to get the stats on our own**
git log --numstat >filename.txt
https://git-scm.com/docs/git-shortlog
https://pavpanchekha.com/blog/paper-section-stats.html
http://blog.vogella.com/2015/09/17/extracting-git-statistics-from-eclipse-platform-ui-in-august/
https://github.com/npalix/gitdm

**Get the stats by using libraries**
https://github.com/npalix/gitdm
https://github.com/ejwa/gitinspector
http://myrepos.branchable.com/
